### ISSUE TITLE
[regression] AttributeError: 'list' object has no attribute 'repo_id'

### ISSUE THREAD

**Issue by alexandrevicenzi** [release-engineering/ubi-population-tool#41]
Error when running ubi-pop and there are packages to associate.

This was caused by #35.

The biggest problem here is not the changes in #35 or this error, but the lack of unit tests, this error could have been avoided if this part of the code was covered by tests.

```
Traceback (most recent call last):
  File "/home/avicenzi/workspace/ubi-population-tool/venv/bin/ubipop", line 11, in <module>
    load_entry_point('ubi-population-tool', 'console_scripts', 'ubipop')()
  File "/home/avicenzi/workspace/ubi-population-tool/ubipop/cli.py", line 68, in entry_point
    main(sys.argv[1:])
  File "/home/avicenzi/workspace/ubi-population-tool/ubipop/cli.py", line 63, in main
    opts.output_repos)\
  File "/home/avicenzi/workspace/ubi-population-tool/ubipop/__init__.py", line 106, in populate_ubi_repos
    self._executor).run_ubi_population()
  File "/home/avicenzi/workspace/ubi-population-tool/ubipop/__init__.py", line 382, in run_ubi_population
    tasks = ft.result()
  File "/home/avicenzi/workspace/ubi-population-tool/venv/lib/python2.7/site-packages/concurrent/futures/_base.py", line 455, in result
    return self.__get_result()
  File "/home/avicenzi/workspace/ubi-population-tool/venv/lib/python2.7/site-packages/concurrent/futures/thread.py", line 63, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/avicenzi/workspace/ubi-population-tool/ubipop/_pulp_client.py", line 194, in associate_modules
    return self.associate_units(src_repo, dst_repo, modules, "modulemd")
  File "/home/avicenzi/workspace/ubi-population-tool/ubipop/_pulp_client.py", line 164, in associate_units
    'source_repo_id': src_repo.repo_id,
AttributeError: 'list' object has no attribute 'repo_id'
```

**Comment by rbikar** [comment]
Actually new code was covered but it had poor asserts.

**Comment by rbikar** [comment]
Fixed by #42
